<Process id="af47bc2c-8feb-43f5-801e-fb32d8fc9ac4" type="process" workType="foreground" name="P_1_네이버증권" version="" designerVersion="3.1.125.00701" lastPublishedServer="" readonly="false" isValid="true" DesignedBy="Designer" Template="" StepCount="7" Orientation="horizontal">
  <Properties>
    <Property key="Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" enabled="True" />
    <Property key="onBefore" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" enabled="True" />
    <Property key="onAfter" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" enabled="True" />
    <Property key="onError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" enabled="True" />
    <Property key="Timeout" controlType="Int32" valueType="System.Int32" formatType="Integer" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="0" />
    <Property key="RunningTime" controlType="Int32" valueType="System.Int32" formatType="Integer" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="261" />
    <Property key="Os" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="Microsoft Windows 10 Pro64비트" />
    <Property key="Resolution" controlType="String" valueType="System.String" formatType="String_Size" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="1920x1080" />
    <Property key="CreatedDate" controlType="String" valueType="System.String" formatType="String_DateTime" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="2025-09-11 10:50:07" />
    <Property key="CreatedBy" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
    <Property key="LastModifiedDate" controlType="String" valueType="System.String" formatType="String_DateTime" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="2025-09-15 16:51:53" />
    <Property key="LastModifiedBy" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="" />
    <Property key="LastPublishedDate" controlType="String" valueType="System.String" formatType="String_DateTime" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
    <Property key="LastPublishedBy" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
  </Properties>
  <LinkItems />
  <Variables />
  <Steps>
    <Step id="S18f7866f9cae40ed896fe36f0a401ace" ver="311241220" createVer="311241220" type="Flow" name="ExecuteScript" dpName="ExecuteScript" dpValue="" dpValue2="" dpImage="" tag="" depth="1" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="deaa4c33-9ce6-45af-9719-bbe9005ce13b" type="Flow">
        <Property type="Flow" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Conditions_Title" controlType="String" valueType="System.String" formatType="String" required="True" visible="True" readonly="False" encrypted="False" isChanged="N" value="저장경로설정" />
        <Property type="Flow" key="Key_Script" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="Global.Naver_flag = true" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[Global.Naver_flag = true]]></Script>
    </Step>
    <Step id="S18a31a9b3e9c40c690e0ba08d9c7974a" ver="311241220" createVer="311241220" type="Flow" name="RunTask" dpName="RunTask" dpValue="" dpValue2="" dpImage="" tag="" depth="1" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="56066e5b-f348-48be-a632-7908d4637560" type="Flow">
        <Property type="Flow" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Conditions_TaskName" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="T_1_1_네이버증권_열기" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[RunTask(this, 'T_1_1_네이버증권_열기', null);]]></Script>
    </Step>
    <Step id="Sbfb71c4aa80a437d9cdb68f8176a04b4" ver="311241220" createVer="311241220" type="Flow" name="RunTask" dpName="RunTask" dpValue="" dpValue2="" dpImage="" tag="" depth="1" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="fe8be32d-99e5-448e-b534-3fcc132472ac" type="Flow">
        <Property type="Flow" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Conditions_TaskName" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="T_1_2_네이버증권_데이터추출" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[RunTask(this, 'T_1_2_네이버증권_데이터추출', null);]]></Script>
    </Step>
    <Step id="S9944931b08b642dc808eec2197407e09" ver="311241220" createVer="311241220" type="Flow" name="DecisionThen" dpName="IfThen" dpValue="Global.Data_use == 'true'" dpValue2="" dpImage="" tag="" depth="1" stmttype="OpenBlock" enabled="True" mainSet="0">
      <Properties id="a7848199-ace0-4f89-8386-09d19bd25af7" type="Flow">
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Conditions_Expression" controlType="PropertyItemTextEditorView" valueType="System.Object" formatType="Condition" required="True" visible="False" readonly="True" encrypted="False" isChanged="N" value="Global.Data_use == 'true'" order="1" />
        <Property type="Flow" key="Conditions_CombineCondition" controlType="PropertyItemCombineConditionView" valueType="System.Boolean" formatType="Boolean" required="False" visible="False" readonly="False" encrypted="False" isChanged="N" value="True" order="2" />
        <Property type="Flow" key="Conditions_Expression1" controlType="PropertyItemExpressionView" valueType="System.Object" formatType="Condition" required="True" visible="True" readonly="False" encrypted="False" isChanged="N" value="Global.Data_use == 'true'" order="3" />
        <Property type="Flow" key="Conditions_AddCondition" controlType="PropertyItemAddConditionView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
      </Properties>
      <RelatedSteps>
        <RelatedStep id="Sa380e172466e41e0b9ac8df328ef1cfc" type="Flow" name="EndDecisionThen" />
      </RelatedSteps>
      <Script><![CDATA[if (Global.Data_use == 'true') {]]></Script>
    </Step>
    <Step id="S1cc74126eb3a4a4e86afc76617c17c3b" ver="311241220" createVer="311241220" type="Flow" name="RunTask" dpName="RunTask" dpValue="" dpValue2="" dpImage="" tag="" depth="2" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="8f156430-b3e5-4042-9bbc-9d7d146a604c" type="Flow">
        <Property type="Flow" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Conditions_TaskName" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="T_1_3_네이버증권_엑셀저장" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[RunTask(this, 'T_1_3_네이버증권_엑셀저장', null);]]></Script>
    </Step>
    <Step id="Se15f22fdceff47f192b59893d73fb344" ver="311241220" createVer="311241220" type="Flow" name="RunTask" dpName="RunTask" dpValue="" dpValue2="" dpImage="" tag="" depth="2" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="9faefd32-9136-4560-8eb7-73ef2f998c44" type="Flow">
        <Property type="Flow" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Conditions_TaskName" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="T_1_4_네이버증권_PDF가공" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[RunTask(this, 'T_1_4_네이버증권_PDF가공', null);]]></Script>
    </Step>
    <Step id="Sa380e172466e41e0b9ac8df328ef1cfc" ver="311241220" createVer="311241220" type="Flow" name="EndDecisionThen" dpName="End-IfThen" dpValue="" dpValue2="" dpImage="" tag="" depth="2" stmttype="CloseBlock" enabled="True" mainSet="0">
      <Properties id="332aaa80-fa8f-4cd4-90f6-950a8a5aab9c" type="Flow">
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
      </Properties>
      <RelatedSteps>
        <RelatedStep id="S9944931b08b642dc808eec2197407e09" type="Flow" name="DecisionThen" />
      </RelatedSteps>
      <Script><![CDATA[}]]></Script>
    </Step>
  </Steps>
  <JScript><![CDATA[function P_1_네이버증권() {

    this.RPAGOTOENABLE = false;
    this.GotoStepRetryCntMap = {};
    this.GotoBlockMap = {4:[7]};
    this.GotoReverseBlockMap = {7:4};
    this.GotoStepBlockTypeMap = {4:'DecisionThen',7:'EndDecisionThen'};


    this.run = function() {

        //------------------------------------------------
        STEP('S18f7866f9cae40ed896fe36f0a401ace', '[1] ExecuteScript');
        Global.Naver_flag = true

        //------------------------------------------------
        STEP('S18a31a9b3e9c40c690e0ba08d9c7974a', '[2] RunTask');
        RunTask(this, 'T_1_1_네이버증권_열기', null);

        //------------------------------------------------
        STEP('Sbfb71c4aa80a437d9cdb68f8176a04b4', '[3] RunTask');
        RunTask(this, 'T_1_2_네이버증권_데이터추출', null);

        //------------------------------------------------
        STEP('S9944931b08b642dc808eec2197407e09', '[4] IfThen');
        if (Global.Data_use == 'true') {

            //------------------------------------------------
            STEP('S1cc74126eb3a4a4e86afc76617c17c3b', '[5] RunTask');
            RunTask(this, 'T_1_3_네이버증권_엑셀저장', null);

            //------------------------------------------------
            STEP('Se15f22fdceff47f192b59893d73fb344', '[6] RunTask');
            RunTask(this, 'T_1_4_네이버증권_PDF가공', null);

        //------------------------------------------------
        }
        STEP('Sa380e172466e41e0b9ac8df328ef1cfc', '[7] End-IfThen');


    }

    this.execute = function() {
        var result = null;
        result = this.run()
        if (result != null)
            return result;
    }
}
]]></JScript>
  <Diagram version="1.300" nodesize="Normal">
    <StepNodes>
      <StepNode step_id="S18f7866f9cae40ed896fe36f0a401ace" group_name="c6823a33-3315-4156-a3c9-0c5a5087f79f_Untitled" folded="False" color="" />
      <StepNode step_id="S18a31a9b3e9c40c690e0ba08d9c7974a" group_name="" folded="False" color="" />
      <StepNode step_id="Sbfb71c4aa80a437d9cdb68f8176a04b4" group_name="" folded="False" color="" />
      <StepNode step_id="S9944931b08b642dc808eec2197407e09" group_name="" folded="False" color="" />
      <StepNode step_id="S1cc74126eb3a4a4e86afc76617c17c3b" group_name="" folded="False" color="" />
      <StepNode step_id="Se15f22fdceff47f192b59893d73fb344" group_name="" folded="False" color="" />
      <StepNode step_id="Sa380e172466e41e0b9ac8df328ef1cfc" group_name="" folded="False" color="" />
    </StepNodes>
  </Diagram>
</Process>