<Process id="667af7e0-2f32-477c-9407-c0ef19d8e2e7" type="process" workType="foreground" name="P_2_DART" version="1.0" designerVersion="3.1.125.00701" readonly="false" isValid="true" DesignedBy="Designer" Template="" StepCount="6" Orientation="horizontal">
  <Properties>
    <Property key="Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" enabled="True" />
    <Property key="onBefore" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" enabled="True" />
    <Property key="onAfter" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" enabled="True" />
    <Property key="onError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" enabled="True" />
    <Property key="Timeout" controlType="Int32" valueType="System.Int32" formatType="Integer" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="0" />
    <Property key="RunningTime" controlType="Int32" valueType="System.Int32" formatType="Integer" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="400" />
    <Property key="Os" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="Microsoft Windows 10 Pro64비트" />
    <Property key="Resolution" controlType="String" valueType="System.String" formatType="String_Size" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="1920x1080" />
    <Property key="CreatedDate" controlType="String" valueType="System.String" formatType="String_DateTime" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="2025-09-11 10:35:28" />
    <Property key="CreatedBy" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
    <Property key="LastModifiedDate" controlType="String" valueType="System.String" formatType="String_DateTime" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="2025-09-16 09:39:51" />
    <Property key="LastModifiedBy" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="" />
    <Property key="LastPublishedDate" controlType="String" valueType="System.String" formatType="String_DateTime" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
    <Property key="LastPublishedBy" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
  </Properties>
  <LinkItems />
  <Variables />
  <Steps>
    <Step id="S497ea2192fba4d7e87b0d730363044d6" ver="311241220" createVer="311241220" type="Flow" name="RunTask" dpName="RunTask" dpValue="" dpValue2="" dpImage="" tag="" depth="1" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="c1cad68a-0a7a-448c-bd79-aaffee43b3bd" type="Flow">
        <Property type="Flow" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Conditions_TaskName" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="T_2_1_DART_열기" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[RunTask(this, 'T_2_1_DART_열기', null);]]></Script>
    </Step>
    <Step id="S46f2b450c7a84f628318833c1e56629b" ver="311241220" createVer="311241220" type="Flow" name="RunTask" dpName="RunTask" dpValue="" dpValue2="" dpImage="" tag="" depth="1" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="42623f27-a608-4425-980b-4d2cc547fbfa" type="Flow">
        <Property type="Flow" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Conditions_TaskName" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="T_2_2_DART_데이터추출" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[RunTask(this, 'T_2_2_DART_데이터추출', null);]]></Script>
    </Step>
    <Step id="Sed1f1b1dda87498785c0228d990fadb9" ver="311241220" createVer="311241220" type="Flow" name="DecisionThen" dpName="IfThen" dpValue="Global.Data_use == true" dpValue2="" dpImage="" tag="" depth="1" stmttype="OpenBlock" enabled="True" mainSet="0">
      <Properties id="a7848199-ace0-4f89-8386-09d19bd25af7" type="Flow">
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Conditions_Expression" controlType="PropertyItemTextEditorView" valueType="System.Object" formatType="Condition" required="True" visible="False" readonly="True" encrypted="False" isChanged="N" value="Global.Data_use == true" order="1" />
        <Property type="Flow" key="Conditions_CombineCondition" controlType="PropertyItemCombineConditionView" valueType="System.Boolean" formatType="Boolean" required="False" visible="False" readonly="False" encrypted="False" isChanged="N" value="True" order="2" />
        <Property type="Flow" key="Conditions_Expression1" controlType="PropertyItemExpressionView" valueType="System.Object" formatType="Condition" required="True" visible="True" readonly="False" encrypted="False" isChanged="N" value="Global.Data_use == true" order="3" />
        <Property type="Flow" key="Conditions_AddCondition" controlType="PropertyItemAddConditionView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
      </Properties>
      <RelatedSteps>
        <RelatedStep id="Sa7e031a088134f119696f1fe01e3dad0" type="Flow" name="EndDecisionThen" />
      </RelatedSteps>
      <Script><![CDATA[if (Global.Data_use == true) {]]></Script>
    </Step>
    <Step id="S7a683405586146a892d74298dd6e0379" ver="311241220" createVer="311241220" type="Flow" name="RunTask" dpName="RunTask" dpValue="" dpValue2="" dpImage="" tag="" depth="2" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="cac20248-1c62-4b9c-bbda-c54c34954166" type="Flow">
        <Property type="Flow" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Conditions_TaskName" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="T_2_3_DART_첨부파일가공" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[RunTask(this, 'T_2_3_DART_첨부파일가공', null);]]></Script>
    </Step>
    <Step id="Sc0ea87dd93f74b03a62c63eb66e93819" ver="311241220" createVer="311241220" type="Flow" name="RunTask" dpName="RunTask" dpValue="" dpValue2="" dpImage="" tag="" depth="2" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="a42fc091-d895-4f59-90ea-a80f46b80eef" type="Flow">
        <Property type="Flow" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Conditions_TaskName" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="T_2_4_DART_엑셀저장" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[RunTask(this, 'T_2_4_DART_엑셀저장', null);]]></Script>
    </Step>
    <Step id="Sa7e031a088134f119696f1fe01e3dad0" ver="311241220" createVer="311241220" type="Flow" name="EndDecisionThen" dpName="End-IfThen" dpValue="" dpValue2="" dpImage="" tag="" depth="2" stmttype="CloseBlock" enabled="True" mainSet="0">
      <Properties id="332aaa80-fa8f-4cd4-90f6-950a8a5aab9c" type="Flow">
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
      </Properties>
      <RelatedSteps>
        <RelatedStep id="Sed1f1b1dda87498785c0228d990fadb9" type="Flow" name="DecisionThen" />
      </RelatedSteps>
      <Script><![CDATA[}]]></Script>
    </Step>
  </Steps>
  <JScript><![CDATA[function P_2_DART() {

    this.RPAGOTOENABLE = false;
    this.GotoStepRetryCntMap = {};
    this.GotoBlockMap = {3:[6]};
    this.GotoReverseBlockMap = {6:3};
    this.GotoStepBlockTypeMap = {3:'DecisionThen',6:'EndDecisionThen'};


    this.run = function() {

        //------------------------------------------------
        STEP('S497ea2192fba4d7e87b0d730363044d6', '[1] RunTask');
        RunTask(this, 'T_2_1_DART_열기', null);

        //------------------------------------------------
        STEP('S46f2b450c7a84f628318833c1e56629b', '[2] RunTask');
        RunTask(this, 'T_2_2_DART_데이터추출', null);

        //------------------------------------------------
        STEP('Sed1f1b1dda87498785c0228d990fadb9', '[3] IfThen');
        if (Global.Data_use == true) {

            //------------------------------------------------
            STEP('S7a683405586146a892d74298dd6e0379', '[4] RunTask');
            RunTask(this, 'T_2_3_DART_첨부파일가공', null);

            //------------------------------------------------
            STEP('Sc0ea87dd93f74b03a62c63eb66e93819', '[5] RunTask');
            RunTask(this, 'T_2_4_DART_엑셀저장', null);

        //------------------------------------------------
        }
        STEP('Sa7e031a088134f119696f1fe01e3dad0', '[6] End-IfThen');


    }

    this.execute = function() {
        var result = null;
        result = this.run()
        if (result != null)
            return result;
    }
}
]]></JScript>
  <Diagram version="1.300" nodesize="Normal">
    <StepNodes>
      <StepNode step_id="S497ea2192fba4d7e87b0d730363044d6" group_name="" folded="False" color="" />
      <StepNode step_id="S46f2b450c7a84f628318833c1e56629b" group_name="" folded="False" color="" />
      <StepNode step_id="Sed1f1b1dda87498785c0228d990fadb9" group_name="" folded="False" color="" />
      <StepNode step_id="S7a683405586146a892d74298dd6e0379" group_name="" folded="False" color="" />
      <StepNode step_id="Sc0ea87dd93f74b03a62c63eb66e93819" group_name="" folded="False" color="" />
      <StepNode step_id="Sa7e031a088134f119696f1fe01e3dad0" group_name="" folded="False" color="" />
    </StepNodes>
  </Diagram>
</Process>