<Process id="bddf2d7b-6929-4ccf-8dd9-2496dc8e2a4a" type="task" workType="foreground" name="T_1_4_DART_엑셀저장" version="" designerVersion="3.1.125.00701" lastPublishedServer="" readonly="false" isValid="true" DesignedBy="Designer" Template="" StepCount="15" Orientation="horizontal">
  <Properties>
    <Property key="Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" enabled="True" />
    <Property key="onBefore" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" enabled="True" />
    <Property key="onAfter" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" enabled="True" />
    <Property key="onError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" enabled="True" />
    <Property key="Timeout" controlType="Int32" valueType="System.Int32" formatType="Integer" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="0" />
    <Property key="RunningTime" controlType="Int32" valueType="System.Int32" formatType="Integer" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="12" />
    <Property key="Os" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="Microsoft Windows 10 Pro64비트" />
    <Property key="Resolution" controlType="String" valueType="System.String" formatType="String_Size" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="1920x1080" />
    <Property key="CreatedDate" controlType="String" valueType="System.String" formatType="String_DateTime" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="2025-09-12 14:46:52" />
    <Property key="CreatedBy" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
    <Property key="LastModifiedDate" controlType="String" valueType="System.String" formatType="String_DateTime" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="2025-09-26 15:47:21" />
    <Property key="LastModifiedBy" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="True" encrypted="False" isChanged="N" value="" />
    <Property key="LastPublishedDate" controlType="String" valueType="System.String" formatType="String_DateTime" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
    <Property key="LastPublishedBy" controlType="String" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
  </Properties>
  <LinkItems />
  <Variables>
    <Variable name="Excel_header" scope="Normal" valueType="Any" formatType="Any" initValue="" desc="" colorValue="#FF377D71" showMarker="False" />
    <Variable name="DART_data" scope="Normal" valueType="Any" formatType="Any" initValue="" desc="" colorValue="#FF7AA874" showMarker="False" />
  </Variables>
  <Steps>
    <Step id="Saebbdf0eb9f04562af9651e8fb27b4ae" ver="311241220" createVer="311241220" type="Pdf" name="ExtractTextFromPdfActivity" dpName="ExtractTextFromPdf" dpValue="Global.file_path + '\DART' + Global.Stock[Global.l] +'\pdf\추출_' + Global.Stock[Global.l] + '.pdf'" dpValue2="" dpImage="" tag="" depth="1" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="e99a78fc-8c82-4884-86a3-36cc489b18eb" type="Pdf">
        <Property type="Pdf" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Pdf" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Pdf" key="Output_Result" controlType="OutputControlType" valueType="System.String" formatType="String" required="True" visible="True" readonly="False" encrypted="False" isChanged="N" value="this.DART_data" />
        <Property type="Pdf" key="Input_File" controlType="PDF" valueType="System.String" formatType="String_FilePath" required="True" visible="True" readonly="False" encrypted="False" isChanged="N" value="Global.file_path + '\\DART\\' + Global.Stock[Global.l] +'\\pdf\\추출_' + Global.Stock[Global.l] + '.pdf'" order="1" />
        <Property type="Pdf" key="Input_Password" controlType="PropertyItemPasswordView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="True" isChanged="Y" encryptedFrom="" value="OFHXrJv2HBkJpaqdsGVnRA==" order="2" />
        <Property type="Pdf" key="Input_PageRange" controlType="String" valueType="System.String" formatType="String" required="True" visible="True" readonly="False" encrypted="False" isChanged="N" value="'All'" order="3" />
        <Property type="Pdf" key="Input_SkipEmptyValue" controlType="Boolean" valueType="System.Boolean" formatType="Boolean" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="False" order="4" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[this.DART_data = ActivityWorker.Play('Pdf', 'ExtractTextFromPdfActivity', this.activitylibraryitem_info_1);]]></Script>
    </Step>
    <Step id="S43c436eb4ef54303b9442e78b2973056" ver="311241220" createVer="311241220" type="Desktop" name="IsFileExist" dpName="IsFileExist" dpValue="RESULT" dpValue2="" dpImage="" tag="" depth="1" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="e381b17d-8c26-43d1-8ed7-c5b365b7c6b7" type="Desktop">
        <Property type="Desktop" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Desktop" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Desktop" key="Command_Path" controlType="File" valueType="System.String" formatType="String_FilePath" required="True" visible="True" readonly="False" encrypted="False" isChanged="N" value="Global.file_path + '\\DART\\' + Global.Stock[Global.l] +'\\보고서_' + Global.Stock[Global.l] + '.xlsx'" />
        <Property type="Desktop" key="Command_Output" controlType="OutputControlType" valueType="System.Boolean" formatType="Variable" required="True" visible="True" readonly="False" encrypted="False" isChanged="N" value="RESULT" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[RESULT = StepPlayer.Run('Desktop.IsFileExist', this.isfileexist_info_2);]]></Script>
    </Step>
    <Step id="Sb44d55c91af446a397c4973b558902a6" ver="311241220" createVer="311241220" type="Flow" name="DecisionThen" dpName="IfThen" dpValue="RESULT != true" dpValue2="" dpImage="" tag="" depth="1" stmttype="OpenBlock" enabled="True" mainSet="0">
      <Properties id="a9691297-7345-4818-ad75-e26eb4748ae0" type="Flow">
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Conditions_Expression" controlType="PropertyItemTextEditorView" valueType="System.Object" formatType="Condition" required="True" visible="False" readonly="True" encrypted="False" isChanged="N" value="RESULT != true" order="1" />
        <Property type="Flow" key="Conditions_CombineCondition" controlType="PropertyItemCombineConditionView" valueType="System.Boolean" formatType="Boolean" required="False" visible="False" readonly="False" encrypted="False" isChanged="N" value="True" order="2" />
        <Property type="Flow" key="Conditions_Expression1" controlType="PropertyItemExpressionView" valueType="System.Object" formatType="Condition" required="True" visible="True" readonly="False" encrypted="False" isChanged="N" value="RESULT != true" order="3" />
        <Property type="Flow" key="Conditions_AddCondition" controlType="PropertyItemAddConditionView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
      </Properties>
      <RelatedSteps>
        <RelatedStep id="S01417c553c14448fbed077ee73a5d2da" type="Flow" name="EndDecisionThen" />
      </RelatedSteps>
      <Script><![CDATA[if (RESULT != true) {]]></Script>
    </Step>
    <Step id="S2b3d22ec172d4ec5aea1a6baa5952e62" ver="311241220" createVer="311241220" type="Excel" name="CreateExcel" dpName="CreateExcel" dpValue="Global.file_path + '\DART' + Global.Stock[Global.l] +'\보고서_' + Global.Stock[Global.l] + '.xlsx'" dpValue2="" dpImage="" tag="" depth="2" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="bd5e9097-f8b0-4e16-8242-f19eddb86336" type="Excel">
        <Property type="Excel" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Excel" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Excel" key="File_Path" controlType="Excel" valueType="System.String" formatType="String_FilePath" required="True" visible="True" readonly="False" encrypted="False" isChanged="N" value="Global.file_path + '\\DART\\' + Global.Stock[Global.l] +'\\보고서_' + Global.Stock[Global.l] + '.xlsx'" />
        <Property type="Excel" key="File_OverWrite" controlType="Boolean" valueType="System.Boolean" formatType="Boolean" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="False" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[StepPlayer.Run('Excel.CreateExcel', this.createexcel_info_4);]]></Script>
    </Step>
    <Step id="S01417c553c14448fbed077ee73a5d2da" ver="311241220" createVer="311241220" type="Flow" name="EndDecisionThen" dpName="End-IfThen" dpValue="" dpValue2="" dpImage="" tag="" depth="2" stmttype="CloseBlock" enabled="True" mainSet="0">
      <Properties id="63820de4-e297-4959-80f7-53d9165e5c66" type="Flow">
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
      </Properties>
      <RelatedSteps>
        <RelatedStep id="Sb44d55c91af446a397c4973b558902a6" type="Flow" name="DecisionThen" />
      </RelatedSteps>
      <Script><![CDATA[}]]></Script>
    </Step>
    <Step id="S23c6cb42cd5e41f7b7692a454357efbc" ver="311241220" createVer="311241220" type="Excel" name="OpenExcel" dpName="OpenExcel" dpValue="Global.file_path + '\DART' + Global.Stock[Global.l] +'\보고서_' + Global.Stock[Global.l] + '.xlsx'" dpValue2="" dpImage="" tag="" depth="1" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="d56bf8a7-8723-4cba-9790-95ab091fc33a" type="Excel">
        <Property type="Excel" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Excel" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Excel" key="Output_OutputExcel" controlType="OutputControlType" valueType="System.Object" formatType="Variable" required="True" visible="True" readonly="False" encrypted="False" isChanged="N" value="RESULT" />
        <Property type="Excel" key="File_Path" controlType="Excel" valueType="System.String" formatType="String_FilePath" required="True" visible="True" readonly="False" encrypted="False" isChanged="N" value="Global.file_path + '\\DART\\' + Global.Stock[Global.l] +'\\보고서_' + Global.Stock[Global.l] + '.xlsx'" order="11" />
        <Property type="Excel" key="File_Invisible" controlType="Boolean" valueType="System.Boolean" formatType="Boolean" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="False" order="12" />
        <Property type="Excel" key="File_ReadOnly" controlType="Boolean" valueType="System.Boolean" formatType="Boolean" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="False" order="16" />
        <Property type="Excel" key="File_Maximize" controlType="Boolean" valueType="System.Boolean" formatType="Boolean" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="True" order="13" />
        <Property type="Excel" key="File_ExecuteShell" controlType="Boolean" valueType="System.Boolean" formatType="Boolean" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="False" order="14" />
        <Property type="Excel" key="File_Timeout" controlType="Int32" valueType="System.Int32" formatType="Integer" required="True" visible="False" readonly="False" encrypted="False" isChanged="N" value="60" order="15" />
        <Property type="Excel" key="File_UsePassword" controlType="Boolean" valueType="System.Boolean" formatType="Boolean" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="False" order="17" />
        <Property type="Excel" key="File_OpenPassword" controlType="PropertyItemPasswordView" valueType="System.String" formatType="String" required="False" visible="False" readonly="False" encrypted="False" isChanged="Y" value="" order="18" />
        <Property type="Excel" key="File_WritePassword" controlType="PropertyItemPasswordView" valueType="System.String" formatType="String" required="False" visible="False" readonly="False" encrypted="False" isChanged="Y" value="" order="19" />
        <Property type="Excel" key="File_TextDelimiter" controlType="PropertyItemDropDownView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="Comma(,)" valuelist="Comma(,);Colon(:);Semicolon(;;);Caret(^);Pipe(|);Tab(&#x9;);Space( );Ampersand(&amp;);Ampersat(@);Asterisk(*);Backslash(\);Dollar($);Dot(.);Equals(=);Exclamation(!);Hyphen(-);Percent(%);Plus(+);Question(?);Sharp(#);Slash(/);Tilde(~);Underscore(_);SystemDynamic(System)" order="20" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[RESULT = StepPlayer.Run('Excel.OpenExcel', this.openexcel_info_6);]]></Script>
    </Step>
    <Step id="S8902f662591f499ca5ba4c0df02fb8f2" ver="311241220" createVer="311241220" type="Flow" name="ExecuteScript" dpName="ExecuteScript" dpValue="" dpValue2="" dpImage="" tag="" depth="1" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="ddb70161-f2ee-4ab3-9eed-cba8ad109048" type="Flow">
        <Property type="Flow" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Conditions_Title" controlType="String" valueType="System.String" formatType="String" required="True" visible="True" readonly="False" encrypted="False" isChanged="N" value="엑셀헤더" />
        <Property type="Flow" key="Key_Script" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="this.Excel_header = []&#xA;this.Excel_header[0] = []&#xD;&#xA;&#xD;&#xA;this.Excel_header[0][0] = Global.Stock[Global.l]&#xD;&#xA;" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[this.Excel_header = []
this.Excel_header[0] = []

this.Excel_header[0][0] = Global.Stock[Global.l]
]]></Script>
    </Step>
    <Step id="S33e773147bfc467d8f0c9fc959a08551" ver="311241220" createVer="311241220" type="Excel" name="WriteRange" dpName="WriteRange" dpValue="ACTIVE_SHEET" dpValue2="" dpImage="" tag="" depth="1" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="52884415-5a8a-4f52-a9ea-f25bee31711d" type="Excel">
        <Property type="Excel" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Excel" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Excel" key="Input_InputExcel" controlType="InputControlType" valueType="System.Object" formatType="Variable" required="True" visible="True" readonly="False" encrypted="False" isChanged="N" value="ACTIVE_EXCEL" />
        <Property type="Excel" key="Input_DataArray" controlType="Object[][]" valueType="System.Object[][]" formatType="Array2D" required="True" visible="True" readonly="False" encrypted="False" isChanged="N" value="this.Excel_header" />
        <Property type="Excel" key="Sheet_SheetName" controlType="String" valueType="System.String" formatType="String" required="True" visible="True" readonly="False" encrypted="False" isChanged="N" value="ACTIVE_SHEET" />
        <Property type="Excel" key="Sheet_StartCell" controlType="String" valueType="System.String" formatType="String" required="True" visible="True" readonly="False" encrypted="False" isChanged="N" value="'A1'" />
        <Property type="Excel" key="File_AutoSave" controlType="Boolean" valueType="System.Boolean" formatType="Boolean" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="False" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[StepPlayer.Run('Excel.WriteRange', this.writerange_info_8);]]></Script>
    </Step>
    <Step id="S00a34d5d1b8d4543adffb2007022a47d" ver="311241220" createVer="311241220" type="Flow" name="Loop" dpName="For" dpValue="this.i &lt; this.DART_data.length + 2" dpValue2="" dpImage="" tag="" depth="1" stmttype="OpenBlock" enabled="True" mainSet="0">
      <Properties id="9da56cc4-e44d-4959-91ef-dc83496c3319" type="Flow">
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Flow" key="Conditions_InitializeIndex" controlType="Object" valueType="System.Object" formatType="Expression" required="True" visible="True" readonly="False" encrypted="False" isChanged="N" value="this.i = 2" />
        <Property type="Flow" key="Conditions_LoopCondition" controlType="Object" valueType="System.Object" formatType="Expression" required="True" visible="True" readonly="False" encrypted="False" isChanged="N" value="this.i &lt; this.DART_data.length + 2" />
        <Property type="Flow" key="Conditions_UpdateIndex" controlType="Object" valueType="System.Object" formatType="Expression" required="True" visible="True" readonly="False" encrypted="False" isChanged="N" value="this.i++" />
      </Properties>
      <RelatedSteps>
        <RelatedStep id="Sc175b92e15074453b79dac43e14e5ead" type="Flow" name="EndLoop" />
      </RelatedSteps>
      <Script><![CDATA[for (this.i = 2; this.i < this.DART_data.length + 2; this.i++) {]]></Script>
    </Step>
    <Step id="S1246783a1b924e36954dbaa80a41f86c" ver="311241220" createVer="311241220" type="Excel" name="WriteRange" dpName="WriteRange" dpValue="ACTIVE_SHEET" dpValue2="" dpImage="" tag="" depth="2" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="52884415-5a8a-4f52-a9ea-f25bee31711d" type="Excel">
        <Property type="Excel" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Excel" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Excel" key="Input_InputExcel" controlType="InputControlType" valueType="System.Object" formatType="Variable" required="True" visible="True" readonly="False" encrypted="False" isChanged="N" value="ACTIVE_EXCEL" />
        <Property type="Excel" key="Input_DataArray" controlType="Object[][]" valueType="System.Object[][]" formatType="Array2D" required="True" visible="True" readonly="False" encrypted="False" isChanged="N" value="this.DART_data[this.i - 2]" />
        <Property type="Excel" key="Sheet_SheetName" controlType="String" valueType="System.String" formatType="String" required="True" visible="True" readonly="False" encrypted="False" isChanged="N" value="ACTIVE_SHEET" />
        <Property type="Excel" key="Sheet_StartCell" controlType="String" valueType="System.String" formatType="String" required="True" visible="True" readonly="False" encrypted="False" isChanged="N" value="'A' + this.i" />
        <Property type="Excel" key="File_AutoSave" controlType="Boolean" valueType="System.Boolean" formatType="Boolean" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="False" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[StepPlayer.Run('Excel.WriteRange', this.writerange_info_10);]]></Script>
    </Step>
    <Step id="Sc175b92e15074453b79dac43e14e5ead" ver="311241220" createVer="311241220" type="Flow" name="EndLoop" dpName="End-For" dpValue="" dpValue2="" dpImage="" tag="" depth="2" stmttype="CloseBlock" enabled="True" mainSet="0">
      <Properties id="f72dc0ac-d7c5-4df9-ba76-6ae7cdb76b76" type="Flow">
        <Property type="Flow" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
      </Properties>
      <RelatedSteps>
        <RelatedStep id="S00a34d5d1b8d4543adffb2007022a47d" type="Flow" name="Loop" />
      </RelatedSteps>
      <Script><![CDATA[}]]></Script>
    </Step>
    <Step id="S24ab58c8e1cf4aa48bf1b6f4c58d6be3" ver="311241220" createVer="311241220" type="Excel" name="SaveExcel" dpName="SaveExcel" dpValue="Global.file_path + '\DART' + Global.Stock[Global.l] +'\보고서_' + Global.Stock[Global.l] + '.csv'" dpValue2="" dpImage="" tag="" depth="1" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="99cdfd3c-ae53-45c1-a68d-821989a1d881" type="Excel">
        <Property type="Excel" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Excel" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Excel" key="Input_InputExcel" controlType="InputControlType" valueType="System.Object" formatType="Variable" required="True" visible="True" readonly="False" encrypted="False" isChanged="N" value="ACTIVE_EXCEL" />
        <Property type="Excel" key="File_SaveAs" controlType="Excel" valueType="System.String" formatType="String_FilePath" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="Global.file_path + '\\DART\\' + Global.Stock[Global.l] +'\\보고서_' + Global.Stock[Global.l] + '.csv'" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[StepPlayer.Run('Excel.SaveExcel', this.saveexcel_info_12);]]></Script>
    </Step>
    <Step id="S905e787ab11449928be146869e026e40" ver="311241220" createVer="311241220" type="Excel" name="CloseExcel" dpName="CloseExcel" dpValue="ACTIVE_EXCEL" dpValue2="" dpImage="" tag="" depth="1" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="8f878f31-80d8-439b-bf46-e2cb8ea6a7f0" type="Excel">
        <Property type="Excel" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Excel" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Excel" key="Input_InputExcel" controlType="InputControlType" valueType="System.Object" formatType="Variable" required="True" visible="True" readonly="False" encrypted="False" isChanged="N" value="ACTIVE_EXCEL" />
        <Property type="Excel" key="File_Force" controlType="Boolean" valueType="System.Boolean" formatType="Boolean" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="False" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[StepPlayer.Run('Excel.CloseExcel', this.closeexcel_info_13);]]></Script>
    </Step>
    <Step id="S438fec5a723d400c9ef326fa708a92eb" ver="311241220" createVer="311241220" type="Desktop" name="DeleteFile" dpName="DeleteFile" dpValue="Global.file_path + '\DART' + Global.Stock[Global.l] +'\보고서_' + Global.Stock[Global.l] + '.xlsx'" dpValue2="" dpImage="" tag="" depth="1" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="c16bb1ca-c0bd-475f-9007-5b833ee61066" type="Desktop">
        <Property type="Desktop" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Desktop" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Desktop" key="Command_Path" controlType="File" valueType="System.String" formatType="String_FilePath" required="True" visible="True" readonly="False" encrypted="False" isChanged="N" value="Global.file_path + '\\DART\\' + Global.Stock[Global.l] +'\\보고서_' + Global.Stock[Global.l] + '.xlsx'" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[StepPlayer.Run('Desktop.DeleteFile', this.deletefile_info_14);]]></Script>
    </Step>
    <Step id="S5164108e7d42447abe9a62ddb396eebe" ver="311241220" createVer="311241220" type="Desktop" name="DeleteDirectory" dpName="DeleteDirectory" dpValue="" dpValue2="" dpImage="" tag="" depth="1" stmttype="Normal" enabled="True" mainSet="0">
      <Properties id="29b225b3-2796-44e6-8388-09ed5cbc4b0e" type="Desktop">
        <Property type="Desktop" key="Options_OnError" controlType="PropertyItemEventHandlerView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Desktop" key="Key_Description" controlType="PropertyItemTextEditorView" valueType="System.String" formatType="String" required="False" visible="True" readonly="False" encrypted="False" isChanged="N" value="" />
        <Property type="Desktop" key="Command_Path" controlType="Folder" valueType="System.String" formatType="String_DirectoryPath" required="True" visible="True" readonly="False" encrypted="False" isChanged="N" value="Global.file_path + '\\DART\\' + Global.Stock[Global.l] +'\\pdf'" />
      </Properties>
      <RelatedSteps />
      <Script><![CDATA[StepPlayer.Run('Desktop.DeleteDirectory', this.deletedirectory_info_15);]]></Script>
    </Step>
  </Steps>
  <JScript><![CDATA[function T_1_4_DART_엑셀저장() {

    this.Excel_header;
    this.DART_data;

    this.RPAGOTOENABLE = false;
    this.GotoStepRetryCntMap = {};
    this.GotoBlockMap = {3:[5],9:[11]};
    this.GotoReverseBlockMap = {5:3,11:9};
    this.GotoStepBlockTypeMap = {3:'DecisionThen',5:'EndDecisionThen',9:'Loop',11:'EndLoop'};


    this.run = function() {

        //------------------------------------------------
        STEP('Saebbdf0eb9f04562af9651e8fb27b4ae', '[1] ExtractTextFromPdf');
        this.DART_data = ActivityWorker.Play('Pdf', 'ExtractTextFromPdfActivity', this.activitylibraryitem_info_1);

        //------------------------------------------------
        STEP('S43c436eb4ef54303b9442e78b2973056', '[2] IsFileExist');
        RESULT = StepPlayer.Run('Desktop.IsFileExist', this.isfileexist_info_2);

        //------------------------------------------------
        STEP('Sb44d55c91af446a397c4973b558902a6', '[3] IfThen');
        if (RESULT != true) {

            //------------------------------------------------
            STEP('S2b3d22ec172d4ec5aea1a6baa5952e62', '[4] CreateExcel');
            StepPlayer.Run('Excel.CreateExcel', this.createexcel_info_4);

        //------------------------------------------------
        }
        STEP('S01417c553c14448fbed077ee73a5d2da', '[5] End-IfThen');

        //------------------------------------------------
        STEP('S23c6cb42cd5e41f7b7692a454357efbc', '[6] OpenExcel');
        RESULT = StepPlayer.Run('Excel.OpenExcel', this.openexcel_info_6);

        //------------------------------------------------
        STEP('S8902f662591f499ca5ba4c0df02fb8f2', '[7] ExecuteScript');
        this.Excel_header = []
        this.Excel_header[0] = []

        this.Excel_header[0][0] = Global.Stock[Global.l]


        //------------------------------------------------
        STEP('S33e773147bfc467d8f0c9fc959a08551', '[8] WriteRange');
        StepPlayer.Run('Excel.WriteRange', this.writerange_info_8);

        //------------------------------------------------
        STEP('S00a34d5d1b8d4543adffb2007022a47d', '[9] For');
        for (this.i = 2; this.i < this.DART_data.length + 2; this.i++) {

            //------------------------------------------------
            STEP('S1246783a1b924e36954dbaa80a41f86c', '[10] WriteRange');
            StepPlayer.Run('Excel.WriteRange', this.writerange_info_10);

        //------------------------------------------------
        }
        STEP('Sc175b92e15074453b79dac43e14e5ead', '[11] End-For');

        //------------------------------------------------
        STEP('S24ab58c8e1cf4aa48bf1b6f4c58d6be3', '[12] SaveExcel');
        StepPlayer.Run('Excel.SaveExcel', this.saveexcel_info_12);

        //------------------------------------------------
        STEP('S905e787ab11449928be146869e026e40', '[13] CloseExcel');
        StepPlayer.Run('Excel.CloseExcel', this.closeexcel_info_13);

        //------------------------------------------------
        STEP('S438fec5a723d400c9ef326fa708a92eb', '[14] DeleteFile');
        StepPlayer.Run('Desktop.DeleteFile', this.deletefile_info_14);

        //------------------------------------------------
        STEP('S5164108e7d42447abe9a62ddb396eebe', '[15] DeleteDirectory');
        StepPlayer.Run('Desktop.DeleteDirectory', this.deletedirectory_info_15);


    }

    this.execute = function() {
        var result = null;
        result = this.run()
        if (result != null)
            return result;
    }
}
]]></JScript>
  <Diagram version="1.300" nodesize="Normal">
    <StepNodes>
      <StepNode step_id="Saebbdf0eb9f04562af9651e8fb27b4ae" group_name="8758e009-5daa-4e54-9cb1-efbcdd870a48_Untitled" folded="False" color="" />
      <StepNode step_id="S43c436eb4ef54303b9442e78b2973056" group_name="4f39c335-1040-405c-8692-1bbab010e99f_Untitled" folded="False" color="" />
      <StepNode step_id="Sb44d55c91af446a397c4973b558902a6" group_name="" folded="False" color="" />
      <StepNode step_id="S2b3d22ec172d4ec5aea1a6baa5952e62" group_name="1e7b7312-6835-47e1-ba94-81a8dff44dc4_엑셀생성" folded="False" color="" />
      <StepNode step_id="S01417c553c14448fbed077ee73a5d2da" group_name="" folded="False" color="" />
      <StepNode step_id="S23c6cb42cd5e41f7b7692a454357efbc" group_name="fc52237e-d69a-418d-b701-3d86a31dba18_엑셀열기" folded="False" color="" />
      <StepNode step_id="S8902f662591f499ca5ba4c0df02fb8f2" group_name="fc52237e-d69a-418d-b701-3d86a31dba18_엑셀열기" folded="False" color="" />
      <StepNode step_id="S33e773147bfc467d8f0c9fc959a08551" group_name="5c3fa493-2f9b-4c85-b4cf-26d61b34e1eb_엑셀열기" folded="False" color="" />
      <StepNode step_id="S00a34d5d1b8d4543adffb2007022a47d" group_name="" folded="False" color="" />
      <StepNode step_id="S1246783a1b924e36954dbaa80a41f86c" group_name="2f3dd738-40a2-458a-ba23-1b5489276c3c_엑셀열기" folded="False" color="" />
      <StepNode step_id="Sc175b92e15074453b79dac43e14e5ead" group_name="" folded="False" color="" />
      <StepNode step_id="S24ab58c8e1cf4aa48bf1b6f4c58d6be3" group_name="5438de12-4765-4260-8569-83be250f3d38_저장 후 닫기" folded="False" color="" />
      <StepNode step_id="S905e787ab11449928be146869e026e40" group_name="5438de12-4765-4260-8569-83be250f3d38_저장 후 닫기" folded="False" color="" />
      <StepNode step_id="S438fec5a723d400c9ef326fa708a92eb" group_name="5438de12-4765-4260-8569-83be250f3d38_저장 후 닫기" folded="False" color="" />
      <StepNode step_id="S5164108e7d42447abe9a62ddb396eebe" group_name="5438de12-4765-4260-8569-83be250f3d38_저장 후 닫기" folded="False" color="" />
    </StepNodes>
  </Diagram>
</Process>